version: '2.3'

services:

  camera-develop:
    image: camera-develop
    build:
      context: ${PWD}/.
      target: develop
    ports:
      - 8080:80
    environment:
      - "TZ=Asia/Tokyo"
    init: true
    volumes_from:
      - camera-volume

  camera-release:
    image: camera-release
    build:
      context: ${PWD}/.
      target: release
    ports:
      - 80:80
    environment:
      - "TZ=Asia/Tokyo"
    init: true

  camera-volume:
    container_name: camera-volume
    hostname: camera-volume
    image: busybox
    volumes:
      - ${PWD}/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/apps:/apps

